# Generated by Django 3.1.3 on 2020-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bloggerIntro',
            field=models.CharField(default='', max_length=50),
        ),
    ]
